steps:

  # Install 
  - name: 'docker'
    args: ['build', '-t', 'django', '.']

  # Migrations
  - name: 'docker'
    args: ['run', 'django', 'python3','manage.py','migrate']

  # Test
  - name: 'docker'
    args: ['run', 'django', 'python3','manage.py','test']    

  # Sonaqube    
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.login=$_SONAR_LOGIN'
    - '-Dsonar.projectKey=$_SONAR_PROJECT_KEY'
    - '-Dsonar.organization=$_SONAR_ORGANIZATION'
    - '-Dsonar.sources=.'

tags: ['cloud-builders-community']    